version: "3"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - /docker/sonarr:/config
      - nashiramedia:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${BASE_DOMAIN:?not set}`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      # - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"

      - "flame.type=application"
      - "flame.name=Sonarr"
      - "flame.url=http://sonarr.${BASE_DOMAIN:?not set}"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
      - sonarr
    restart: always

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - AUTO_UPDATE=true #optional
    volumes:
      - /docker/jackett:/config
      # - download:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${BASE_DOMAIN:?not set}`)"
      - "traefik.http.routers.jackett.entrypoints=web"
      - "traefik.http.routers.jackett.service=jackett"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      # - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"

      - "flame.type=application"
      - "flame.name=Jackett"
      - "flame.url=http://jackett.${BASE_DOMAIN:?not set}"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
      - sonarr
    restart: always
    
volumes:
  nashiramedia:
    driver_opts:
      type: nfs
      o: "addr=192.168.5.9,nolock,soft,rw,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":/mnt/tank8tb/media/"

networks:
  traefik:
    external: true
  sonarr:
    name: sonarr
    internal: true