version: "3"

services:
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    environment:
      - USER_UID=${UID:?not_set}
      - USER_GID=${GID:?not_set}
      - TZ=${TIMEZONE:?notset}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_DATABASE_PASS:?not set}
      - GITEA__server__ROOT_URL=http://git.${BASE_DOMAIN:?not_set}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.${BASE_DOMAIN:?not_set}`)"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

      - "flame.type=application"
      - "flame.name=gitea"
      - "flame.url=http://git.${BASE_DOMAIN:?not_set}"
    networks:
      - traefik
      - gitea-db
    ports:
      - "2222:22"
    volumes:
      - /docker/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      - gitea-db

  gitea-db:
    image: postgres:13-alpine
    container_name: gitea-db
    restart: unless-stopped
    environment:
      - "POSTGRES_DB=gitea"
      - "POSTGRES_USER=gitea"
      - "POSTGRES_PASSWORD=${GITEA_DATABASE_PASS:?not set}"
    networks:
      - gitea-db
    volumes:
      - /docker/gitea/database:/var/lib/postgresql/data


networks:
  traefik:
    external: true
  gitea-db:
    name: gitea-db
    internal: true