version: "3"

## https://github.com/pi-hole/docker-pi-hole
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
      - 192.168.5.1
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: '${WEBPASSWORD:?not set}'
      PIHOLE_DNS_: 192.168.5.1
      DNSSEC: 'true'
      ServerIP: 192.168.5.3 # Actual server IP. Matches DHCP conf file IP
      VIRTUAL_HOST: pihole.${BASE_DOMAIN:?not set} # Same as port traefik config
      DNSMASQ_LISTENING: all
      DHCP_ACTIVE: 'false'
      WEBTHEME: default-dark
      PIHOLE_DOMAIN: ${BASE_DOMAIN:?not set}
      TEMPERATUREUNIT: c
      REV_SERVER: 'true'
      REV_SERVER_DOMAIN: "${BASE_DOMAIN:?not set}"
      REV_SERVER_TARGET: 192.168.5.1
      REV_SERVER_CIDR: "192.168.0.0/16"
    volumes:
      - '/docker/pihole:/etc/pihole/'
      - '/docker/dnsmasq.d:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: always
    networks: 
      traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${BASE_DOMAIN:?not set}`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=web"
      # - "traefik.http.routers.pihole.tls.certresolver=letsencrypt"

      - "flame.type=application"
      - "flame.name=Pi-Hole"
      - "flame.url=http://pihole.${BASE_DOMAIN:?not set}"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks: 
  traefik:
    external: true