version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - PUID=${UID:?not set}
      - PGID=${GID:?not set}
      - TZ=${TIMEZONE:?not set}
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      # - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      # - "--web.console.templates=/usr/share/prometheus/consoles"
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker/prometheus/data:/prometheus
    expose:
      - 9090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${BASE_DOMAIN:?not set}`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      # - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
      - "traefik.http.routers.prometheus.middlewares=compress"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

      - "flame.type=application"
      - "flame.name=Prometheus"
      - "flame.url=http://prometheus.${BASE_DOMAIN:?not set}"
    networks:
      - traefik

  grafana:
    image: grafana/grafana:8.4.6
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    environment:
      - PUID=${UID:?not set}
      - PGID=${GID:?not set}
      - TZ=${TIMEZONE:?not set}
      - "GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:?not set}"
      - "GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:?not set}"
      - "GF_ALERTING_ENABLED=false"
      - "GF_AUTH_ANONYMOUS_ENABLED=false"
      - "GF_DEFAULT_INSTANCE_NAME=grafana.${BASE_DOMAIN:?not set}"
      # - "GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel"
      - "GF_METRICS_ENABLED=true"
      # - "GF_SECURITY_COOKIE_SECURE=true"
      - "GF_SECURITY_COOKIE_SAMESITE=disabled"
      - "GF_SECURITY_DISABLE_GRAVATAR=true"
      - "GF_SECURITY_ALLOW_EMBEDDING=false"
      - "GF_SERVER_DOMAIN=grafana.${BASE_DOMAIN:?not set}"
      - "GF_SERVER_ENFORCE_DOMAIN=true"
      - "GF_SERVER_HTTP_PORT=3000"
      # - "GF_SERVER_HTTP_PROTOCOL=https"
      - "GF_SERVER_ROOT_URL=http://grafana.${BASE_DOMAIN:?not set}/"
      - "GF_SERVER_SERVE_FROM_SUB_PATH=false"
      - "GF_SNAPSHOTS_EXTERNAL_ENABLED=false"
      - "GF_USERS_ALLOW_SIGN_UP=false"
      - "GF_USERS_VIEWERS_CAN_EDIT=false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - /docker/grafana/data:/var/lib/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${BASE_DOMAIN:?not set}`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      # - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.routers.grafana.middlewares=compress"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

      - "flame.type=application"
      - "flame.name=Grafana"
      - "flame.url=http://grafana.${BASE_DOMAIN:?not set}"
    expose:
      - 3000
    networks:
      - traefik

  # loki:
  #   container_name: loki
  #   image: grafana/loki:2.3.0
  #   restart: unless-stopped
  #   expose:
  #     - 3100
  #   volumes:
  #     - ./loki-config.yml:/etc/loki/loki-config.yaml:ro
  #     - /docker/loki/data:/data/loki
  #   command: 
  #     - "-config.file=/etc/loki/loki-config.yaml"
  #   labels:
  #     - "traefik.enable=false"
  #   networks:
  #     - traefik

  nodeexporter:
    image: prom/node-exporter:v1.3.1
    container_name: nodeexporter
    environment:
      - PUID=${UID:?not set}
      - PGID=${GID:?not set}
      - TZ=${TIMEZONE:?not set}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - traefik
    labels:
      - "traefik.enable=false"
      # - org.label-schema.group: "monitoring"

  cadvisor:
    image: zcube/cadvisor:latest
    container_name: cadvisor
    privileged: true
    environment:
      - PUID=${UID:?not set}
      - PGID=${GID:?not set}
      - TZ=${TIMEZONE:?not set}
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - traefik
    labels:
      - "traefik.enable=false"
      # org.label-schema.group: "monitoring"

networks:
  traefik:
    external: true