version: "3"

services:
  traggo:
    image: traggo/server:latest
    container_name: traggo
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traggo.rule=Host(`traggo.${BASE_DOMAIN:?not set}`)"
      - "traefik.http.routers.traggo.entrypoints=web"

      - "flame.type=application"
      - "flame.name=Traggo"
      - "flame.url=http://traggo.${BASE_DOMAIN:?not set}"
      
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    volumes:
      - /docker/traggo:/opt/traggo/data
    restart: unless-stopped

networks:
  traefik:
    external: true